(function($){
    $(function(){
        //按钮添加hover样式
        $('input.submit,input.button').hover(function(){
            $(this).addClass('ui-state-hover')
        },function(){
            $(this).removeClass('ui-state-hover')
        });
        //board添加theme
    });
})(jQuery);
